
autoencoder:
  batch_size: 32
  num_epochs: 40
  hidden_1: 10
  hidden_state_size: 5

lstm:
  learning_rate: 0.00002
  dropout_prob: 0.5
  windows_size: 100
  output_window: 15
  rnn_hidden: 200
  num_epochs: 2
  from_file: False

portfolio:
  frequency: 30
  risk_aversion: 80
  frequency_optimize_lstm: 120

